MagicVilla_Web/Controllers/AuthController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace MagicVilla_Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly IMapper _mapper;

        public AuthController(IAuthService authService, IMapper mapper)
        {
            _authService = authService;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDto obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDto dto)
        {
             APIResponse response = await _authService.LoginAsync<APIResponse>(dto);

            if (response != null && response.IsSuccess)
            {
                LoginResponseDto responseObj = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(response.Result));

                //to get name and role info from the token
                var handler = new JwtSecurityTokenHandler();
                var jwt = handler.ReadJwtToken(responseObj.Token);


                //so the httpcontext knows that user is logged in - actually signing in a user
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(u => u.Type == "unique_name").Value));
                identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u=>u.Type=="role").Value));
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                //now user is singed together with claims

                //we retrieve token from responseObj and store it in session
                HttpContext.Session.SetString(StaticDetails.SessionToken, responseObj.Token);


                TempData["success"] = "Login was successful!";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("CustomError", response.ErrorMessages.FirstOrDefault());
                return View(dto);
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            RegistrationRequestDto obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegistrationRequestDto dto)
        {
            
            var response = await _authService.RegisterAsync<APIResponse>(dto);

            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Registration was successful!";
                return RedirectToAction("Login");
            }
            

            TempData["error"] = "Error encountered!!";

            return View(dto);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString(StaticDetails.SessionToken, "");
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;

        public VillaController(IVillaService villaService, IMapper mapper)
        {
            _villaService = villaService;
            _mapper = mapper;
        }
        public async Task<IActionResult> IndexVilla()
        {
            List<VillaDto> list = new();

            var response = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess) {
                //we get all datafrom response in response.Result, we deserialize it, convert it to 
                //List of VillaDto type and assign it to our list
                list = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        [Authorize(Roles ="admin")]
        public async Task<IActionResult> CreateVilla()
        {
            //List<VillaDto> list = new();

            //var response = await _villaService.GetAllAsync<APIResponse>();
            //if (response != null && response.IsSuccess)
            //{
            //    //we get all datafrom response in response.Result, we deserialize it, convert it to 
            //    //List of VillaDto type and assign it to our list
            //    list = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Result));
            //}

            VillaCreateDto dto = new VillaCreateDto();

            return View(dto);
        }
        [Authorize(Roles ="admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVilla(VillaCreateDto dto)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.CreateAsync<APIResponse>(dto, HttpContext.Session.GetString(StaticDetails.SessionToken));

                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Villa created successfully!";
                    return RedirectToAction("IndexVilla");
                }
            }

            TempData["error"] = "Error encountered!!";

            return View(dto);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(int id)
        {
            var resp = await _villaService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken));

            if(resp != null && resp.IsSuccess)
            {
                VillaDto villaDto = JsonConvert.DeserializeObject<VillaDto>(Convert.ToString(resp.Result));
                return View(_mapper.Map<VillaUpdateDto>(villaDto));
            }

            return NotFound();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVilla(VillaUpdateDto dto)
        {
            if (ModelState.IsValid)
            {
                TempData["success"] = "Villa updated successfully!";

                var response = await _villaService.UpdateAsync<APIResponse>(dto, HttpContext.Session.GetString(StaticDetails.SessionToken));

                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction("IndexVilla");
                }
            }

            TempData["error"] = "Error encountered!!";

            return View(dto);
        }

      
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVilla(int id)
        {
            var response = await _villaService.DeleteAsync<APIResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken));

            
            if (response !=null && response.IsSuccess)
            {
                TempData["success"] = "Villa deleted successfully!";

                return RedirectToAction("IndexVilla");
            }

            TempData["error"] = "Error encountered!!";
         
            return NotFound();
        }
    }
}

MagicVilla_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto;
using MagicVilla_Web.Models.VM;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Data;
using System.Net;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;

        public VillaNumberController(IVillaNumberService villaNumberService, IVillaService villaService, IMapper mapper)
        {
            _villaNumberService = villaNumberService;
            _villaService = villaService;   
            _mapper = mapper;
        }
        public async Task<IActionResult> IndexVillaNumber()
        {
            List<VillaNumberDto> listVillaNumbers = new();

            var resp = await _villaNumberService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));

            if (resp != null && resp.IsSuccess)
            {
                listVillaNumbers = JsonConvert.DeserializeObject<List<VillaNumberDto>>(Convert.ToString(resp.Result));
            }

            return View(listVillaNumbers);
        }

        [Authorize(Roles = "admin")]

        public async Task<IActionResult> CreateVillaNumber()
        {
          
            VillaNumberCreateVM villaNumberCreateVM = new VillaNumberCreateVM();

            var resp = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));

            if(resp !=null && resp.IsSuccess)
            {
                villaNumberCreateVM.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(resp.Result))
                    .Select(x=> new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name,
                    });
            }

            //var villaSelectist = villaList.Select(s => new { s.Id, Name = s.Name }).ToList();

            return View(villaNumberCreateVM);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM villaNumberCreateVM)
        {
            if(ModelState.IsValid)
            {
                var resp = await _villaNumberService.CreateAsync<APIResponse>(villaNumberCreateVM.VillaNumber, HttpContext.Session.GetString(StaticDetails.SessionToken));

                if (resp != null && resp.IsSuccess)
                {
                    TempData["success"] = "Villa Number created successfully!";

                    return RedirectToAction("IndexVillaNumber");
                }
                else
                {
                    if(resp.ErrorMessages.Count>0)
                    {
                        ModelState.AddModelError("CustomError", resp.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            TempData["error"] = "Error encountered!!";


            //when MoelState not valid, repopulate villa list
            var allVillas = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));

            if (allVillas != null && allVillas.IsSuccess)
            {
                villaNumberCreateVM.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(allVillas.Result))
                    .Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name,
                    });
            }

            return View(villaNumberCreateVM);
        }


        // [HttpPut("{id}")]
        [Authorize(Roles = "admin")]

        public async Task<IActionResult> UpdateVillaNumber(int id)
        {
            VillaNumberUpdateVM villaNumberUpdateVM = new VillaNumberUpdateVM();

            var resp = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));

            if (resp != null && resp.IsSuccess)
            {
                villaNumberUpdateVM.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(resp.Result))
                    .Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name,
                    });
            }

            var getVillaNumber = await _villaNumberService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken));

            if (getVillaNumber != null && getVillaNumber.IsSuccess)
            {
                VillaNumberDto villaNumDto = JsonConvert.DeserializeObject<VillaNumberDto>(Convert.ToString(getVillaNumber.Result));
                villaNumberUpdateVM.VillaNumber  = _mapper.Map<VillaNumberUpdateDto>(villaNumDto);

                return View(villaNumberUpdateVM);

            }

            return NotFound();

            //_response.Result = _mapper.Map<VillaDto>(villa);

            //var villaNum = _mapper.Map<VillaNumberDto>(getVillaNumber.Result);

            //VillaNumberUpdateDto dto = new VillaNumberUpdateDto
            //{
            //    VillaList = new SelectList(villaSelectist, "Id", "Name"),
            //    VillaNo = villaNum.VillaNo
            //};

            //return View(dto);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM villaNumberUpdateVM)
        {
            if (ModelState.IsValid)
            {
                var resp = await _villaNumberService.UpdateAsync<APIResponse>(villaNumberUpdateVM.VillaNumber, HttpContext.Session.GetString(StaticDetails.SessionToken));

                if (resp != null && resp.IsSuccess)
                {
                    TempData["success"] = "Villa Number updated successfully!";

                    return RedirectToAction("IndexVillaNumber");
                }
                else
                {
                    if(resp.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", resp.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            TempData["error"] = "Error encountered!!";


            var allVillas = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));

            if (allVillas != null && allVillas.IsSuccess)
            {
                villaNumberUpdateVM.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(allVillas.Result))
                    .Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name,
                    });
            }


            return View(villaNumberUpdateVM);
        }

        [Route("api/v1/villaNumber/DeleteVillaNumber")]
        [Authorize(Roles = "admin")]
        [HttpDelete("{id:int}")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteVillaNumber(int id)
        {
            var response = await _villaNumberService.DeleteAsync<APIResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken));


            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Villa Number deleted successfully!";

                return RedirectToAction(nameof(IndexVillaNumber));
            }

            TempData["error"] = "Error encountered!!";


            return RedirectToAction(nameof(IndexVillaNumber));
        }
    }
}

MagicVilla_Web/Views/Shared/_Layout.cshtml
@using MagicVilla_Utility;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicVilla_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicVilla_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MagicVilla_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Villa Numbers</a>
                        </li>

                        @if(httpAcc.HttpContext.Session.GetString(StaticDetails.SessionToken) !=null &&
                            httpAcc.HttpContext.Session.GetString(StaticDetails.SessionToken).ToString().Length>0)
                       {
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                           </li>
                        }else
                        {
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                           </li>
                      
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MagicVilla_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MagicVilla_Web/Views/Shared/_Notification.cshtml
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if(TempData["success"]!=null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 2000,
            timerProgressBar: true
        })
    </script>
}

@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 2000,
            timerProgressBar: true
        })
    </script>
}